### ISSUE TITLE
pygame.draw.rect(self.windowSurface, color, ValueError: invalid color argument

### ISSUE THREAD

**Issue by davidky3000** [maudoin/ollama-voice#4]
After opening, it will flash by and prompt the following questions:
Traceback (most recent call last):
  File "d:\08 Whisper\OllamaVoice-main\OllamaVoice-main\assistant.py", line 299, in <module>
    main()
  File "d:\08 Whisper\OllamaVoice-main\OllamaVoice-main\assistant.py", line 278, in main
    ass = Assistant()
  File "d:\08 Whisper\OllamaVoice-main\OllamaVoice-main\assistant.py", line 66, in __init__
    self.text_to_speech(self.config.messages.loadingModel)
  File "d:\08 Whisper\OllamaVoice-main\OllamaVoice-main\assistant.py", line 265, in text_to_speech
    self.display_sound_energy(energy_of_chunk)
  File "d:\08 Whisper\OllamaVoice-main\OllamaVoice-main\assistant.py", line 152, in display_sound_energy
    pygame.draw.rect(self.windowSurface, color,
ValueError: invalid color argument

**Comment by RegolithIII** [comment]
For me, it runs until it starts to answer and show the same error

**Comment by RegolithIII** [comment]
Update : I got it to work by replacing `color = (RED_CENTER+(FACTOR*(i % mid)), 0, 0)` in line 150 by `color = (255, 255, 255)`
